#include <iostream>
#include "header.hpp"

auto Documentation::guide() -> void {
    std::cout << "This is small guide on usage of program\n"
              << "[1] Search for password(s) - In this part I didn't had any good ideas to be honest\n"
              << "You have to enter a password to find out if it is present in any of the lists. "
              << " And after that it gives you the proper message about if password found or not\n\n"
              << "[2] Sort password(s)\n"
              << "It automatically sorts the passwords, I used multimap and std::sort for sorting"
              << " and I think it is not practically the best way to do that, I could have used projection argument"
              << " or custom comparators\n\n"
              << "[3] Add/Print password(s)\n"
              << R"(I would say this is the most important part of the program, because I have "Generator", "Create passwords")"
              << "\"URLs with passwords\" and etc.\n"
              << "User first will see [1] \"Create Password\" option. This allows user to create its own password with all the safety check"
              << "Safety check iterates through password char by char and checks them if they are uppercase, lowercase, special and etc."
              << " Also if user's password is considered weak, it require from him for confirmation to add it to password list\n"
              << "Each password has its own unique key, which will be used in user inputs, I chose to create random keys, "
              << " because I think that I have two options, either I will require from user to type whole password or key, "
              << " and I decided that in most cases writing down keys are easier for users\n\n"
              << "[2] Password Generator\n"
              << "I learned whole random library for that it was a bit painful :), But when I used rand(), I saw that some keys were generated same"
              << " so I kept overriding the same value.\n"
              << "In case of generator it has 4 options with all the possibilities between \"Lowercase, Uppercase, Special Character and Numbers\"\n"
              << "User has to enter the size and size has to be bigger than 4"
              << "[3] Create password with url\n"
              << "So you could say why tf I have \"create passwords with url\", But I thought that if the password will have URL,"
              << " why do I need add it to category, I think URL is similar to category, so I made them separate\n\n"
              << "[4] Print password list\n"
              << "It prints the passwords in the password list, simple and easy\n\n"
              << "[5] Print categories with passwords\n"
              << "It is printing the categories, also simple and easy\n\n"
              << "[6] Add password to the category\n"
              << "User could add all the passwords from the password list to the categories\n\n"
              << "[4] Edit password(s)\n"
              << "This class is used for editing existing passwords, so the user must choose the password by its ID and"
              << R"( enters the new password, it is more like "replace password" than "edit password")"
              << "\n\n[5] Remove password(s)\n"
              << "Well I think those names are self explanatory"
              << "Wait I think I am running out of time it is 10:40 of the deadline day and I am writing this stupid guide that no-one will read"
              << "Anyways I hope I'll get good points :>\n" << std::endl;
}
